// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"sakura/aurora/rpc/user/internal/logic/authenticate"
	"sakura/aurora/rpc/user/internal/svc"
	"sakura/aurora/rpc/user/types"
)

type AuthenticateServer struct {
	svcCtx *svc.ServiceContext
	types.UnimplementedAuthenticateServer
}

func NewAuthenticateServer(svcCtx *svc.ServiceContext) *AuthenticateServer {
	return &AuthenticateServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthenticateServer) Username(ctx context.Context, in *types.UsernameAndPassword) (*types.Authenticated, error) {
	l := authenticatelogic.NewUsernameLogic(ctx, s.svcCtx)
	return l.Username(in)
}
